package shell

import (
	"fmt"
	"strings"
)

// commands is the list of all top-level commands that chop supports.
// Keep in sync with the switch in filters.Get().
var commands = []string{
	"git", "npm", "npx", "pnpm", "yarn", "bun",
	"docker", "dotnet", "kubectl", "helm", "terraform",
	"cargo", "go", "tsc", "eslint", "biome",
	"gh", "grep", "rg",
	"curl", "http",
	"aws", "az", "gcloud",
	"mvn", "gradle", "gradlew",
	"ng", "nx",
	"pytest", "pip", "pip3", "uv", "mypy", "ruff", "flake8", "pylint",
	"bundle", "bundler", "rspec", "rubocop",
	"composer",
	"make", "cmake",
	"gcc", "g++", "cc", "c++", "clang", "clang++",
	"ping", "ps", "ss", "netstat", "df", "du",
}

// GenerateInit returns shell code that wraps supported commands through chop.
// Supported shell types: "bash", "zsh", "fish", "powershell"/"pwsh".
func GenerateInit(shellType string) string {
	switch shellType {
	case "bash", "zsh":
		return generateBashZsh()
	case "fish":
		return generateFish()
	case "powershell", "pwsh":
		return generatePowerShell()
	default:
		return fmt.Sprintf("echo \"chop: unsupported shell %q (use bash, zsh, fish, or powershell)\" >&2\n", shellType)
	}
}

func generateBashZsh() string {
	var b strings.Builder

	b.WriteString("# chop shell integration\n")
	b.WriteString("# Generated by: eval \"$(chop init bash)\"  or  eval \"$(chop init zsh)\"\n")
	b.WriteString("# Wraps supported commands so their output is automatically filtered through chop.\n")
	b.WriteString("#\n")
	b.WriteString("# Use 'unchop <command> [args...]' to bypass chop and run the original command.\n\n")

	b.WriteString("__chop_wrap() {\n")
	b.WriteString("    command chop \"$@\"\n")
	b.WriteString("}\n\n")

	for _, cmd := range commands {
		// Identifiers with + need quoting — but bash function names can't contain +.
		// Use underscores for the alias approach instead.
		if isValidBashFunctionName(cmd) {
			b.WriteString(fmt.Sprintf("%s() { __chop_wrap %s \"$@\"; }\n", cmd, cmd))
		}
	}

	b.WriteString("\n# Bypass: run the original command without chop\n")
	b.WriteString("unchop() { command \"$@\"; }\n")

	return b.String()
}

func generateFish() string {
	var b strings.Builder

	b.WriteString("# chop shell integration\n")
	b.WriteString("# Generated by: chop init fish | source\n")
	b.WriteString("# Wraps supported commands so their output is automatically filtered through chop.\n")
	b.WriteString("#\n")
	b.WriteString("# Use 'unchop <command> [args...]' to bypass chop and run the original command.\n\n")

	b.WriteString("function __chop_wrap\n")
	b.WriteString("    command chop $argv\n")
	b.WriteString("end\n\n")

	for _, cmd := range commands {
		if isValidFishFunctionName(cmd) {
			b.WriteString(fmt.Sprintf("function %s; __chop_wrap %s $argv; end\n", cmd, cmd))
		}
	}

	b.WriteString("\n# Bypass: run the original command without chop\n")
	b.WriteString("function unchop; command $argv; end\n")

	return b.String()
}

func generatePowerShell() string {
	var b strings.Builder

	b.WriteString("# chop shell integration for PowerShell\n")
	b.WriteString("# Add to your $PROFILE:\n")
	b.WriteString("#   chop init powershell | Invoke-Expression\n")
	b.WriteString("# Or for permanent setup:\n")
	b.WriteString("#   Add-Content $PROFILE (chop init powershell)\n")
	b.WriteString("#\n")
	b.WriteString("# Use 'unchop <command> [args...]' to bypass chop and run the original command.\n\n")

	for _, cmd := range commands {
		if !isValidPowerShellFunctionName(cmd) {
			continue
		}
		b.WriteString(fmt.Sprintf("function %s { chop %s @args }\n", cmd, cmd))
	}

	b.WriteString("\n# Bypass: run the original command without chop\n")
	b.WriteString("function unchop { & $args[0] $args[1..($args.Count-1)] }\n")

	return b.String()
}

// isValidPowerShellFunctionName returns true if the name can be used as a PowerShell function.
// PowerShell function names can't start with digits and ++ is problematic.
func isValidPowerShellFunctionName(name string) bool {
	for _, ch := range name {
		if ch == '+' {
			return false
		}
	}
	return true
}

// isValidBashFunctionName returns true if the name can be used as a bash function.
// Bash function names can contain letters, digits, underscores, and some special chars,
// but NOT '+'. We handle g++, c++, clang++ via aliases instead of functions.
func isValidBashFunctionName(name string) bool {
	for _, ch := range name {
		if ch == '+' {
			return false
		}
	}
	return true
}

// isValidFishFunctionName checks if name is valid for a fish function.
// Fish is more permissive but we apply the same rule for consistency.
func isValidFishFunctionName(name string) bool {
	return isValidBashFunctionName(name)
}
